---

Parameters:
  WindowsAmi:
    Type: AWS::EC2::Image::Id
  InstanceType:
    Type: String

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 90

  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref AWS::StackName

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and RDP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0 # This is bad.

  ElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref SteamMachine

  SteamMachine:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            C:\cfn\cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
            C:\cfn\hooks.d\cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.SteamMachine.Metadata.AWS::CloudFormation::Init
                action=cfn-init.exe -v -s ${AWS::StackId} -r SteamMachine --region ${AWS::Region}
            C:\SteamSetup.exe:
              source: https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe
          commands:
            1_initilize_audio:
              command: sc config AudioSrv start= auto
              waitAfterCompletion: 5
            2_add_user: # This is awful.
              command: net user /add Gary Secret123
              waitAfterCompletion: 5
            3_add_user_to_admin_group:
              command: net localgroup administrators Gary /add
              waitAfterCompletion: 5
            4_install_steam:
              command: C:\SteamSetup.exe /S
            5_reboot:
              command: shutdown -r -t 0
              waitAfterCompletion: forever
          services:
            windows:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - C:\cfn\cfn-hup.conf
                  - C:\cfn\hooks.d\cfn-auto-reloader.conf
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref WindowsAmi
      SecurityGroups:
        - !Ref SecurityGroup
      KeyName: !Ref KeyPair
      Monitoring: true
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
      UserData:
        Fn::Base64:
          !Sub
            - |
              <script>
              cfn-init.exe -v -s ${stack_id} -r SteamMachine --region ${region}
              cfn-signal.exe -e %ERRORLEVEL% ${wait_condition_handle}
              </script>
            - stack_id: !Ref AWS::StackId
              region: !Ref AWS::Region
              wait_condition_handle:
                Fn::Base64:
                  !Ref WaitConditionHandle

  WaitConditionHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  WaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: SteamMachine
    Properties:
      Handle: !Ref WaitConditionHandle
      Timeout: 3600
