---

Parameters:
  WindowsUsername:
    Type: String
    NoEcho: true
  WindowsPassword:
    Type: String
    NoEcho: true

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 90

  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref AWS::StackName

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and RDP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0 # This is bad.

  GameMachine1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: game-machine.template.yaml
      Parameters:
        Name: !Sub ${AWS::StackName}-1
        InstanceType: t3.large
        Username: !Ref WindowsUsername
        Password: !Ref WindowsPassword
        SecurityGroupId: !Ref SecurityGroup
        KeyPairName: !Ref KeyPair

  GameMachine2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: game-machine.template.yaml
      Parameters:
        Name: !Sub ${AWS::StackName}-2
        InstanceType: t3.large
        Username: !Ref WindowsUsername
        Password: !Ref WindowsPassword
        SecurityGroupId: !Ref SecurityGroup
        KeyPairName: !Ref KeyPair
