---

Parameters:
  WindowsAmi:
    Type: AWS::EC2::Image::Id
  InstanceType:
    Type: String

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 90

  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref AWS::StackName

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and RDP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0 # TODO: This is bad.

  ElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref SteamMachine

  SteamMachine:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            c:\cfn\cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
            c:\cfn\hooks.d\cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.SteamMachine.Metadata.AWS::CloudFormation::Init
                action=cfn-init.exe -v -s ${AWS::StackId} -r SteamMachine --region ${AWS::Region}
            C:\Users\Public\Desktop\DisplayAdapter.bat:
              content: |
                takeown /f C:\Windows\System32\Drivers\BasicDisplay.sys
                cacls C:\Windows\System32\Drivers\BasicDisplay.sys /G Administrators:F
                del C:\Windows\System32\Drivers\BasicDisplay.sys
            C:\Users\Public\Desktop\Startup.bat:
              content: md Z:\SteamLibrary
            C:\Users\Public\Desktop\FileExtensions.bat:
              content: reg add HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v HideFileExt /t REG_DWORD /d 0 /f
            C:\SteamSetup.exe:
              source: https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe
          commands:
            1-Install Steam:
              command: 'C:\SteamSetup.exe /S'
            2-Disable IE Enhanced Security:
              command: REG ADD "HKLM\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}" /v IsInstalled /t REG_DWORD /d 00000000 /f
            3-Disable Windows Firewall:
              command: netsh advfirewall set allprofiles state off
            4-Set Windows Audio to Automatic startup:
              command: sc config AudioSrv start= auto
          services:
            windows:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - 'c:\cfn\cfn-hup.conf'
                  - 'c:\cfn\hooks.d\cfn-auto-reloader.conf'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref WindowsAmi
      SecurityGroups:
        - !Ref SecurityGroup
      KeyName: !Ref KeyPair
      Monitoring: true
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
      UserData:
        Fn::Base64:
          !Sub
            - |
              <script>
              cfn-init.exe -v -s ${stack_id} -r SteamMachine --region ${region}
              cfn-signal.exe -e %ERRORLEVEL% ${wait_condition_handle}
              </script>
            - stack_id: !Ref AWS::StackId
              region: !Ref AWS::Region
              wait_condition_handle:
                Fn::Base64:
                  !Ref WaitConditionHandle

  WaitConditionHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  WaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: SteamMachine
    Properties:
      Handle: !Ref WaitConditionHandle
      Timeout: 3600
