name: Deploy

on:
  workflow_dispatch:
    inputs:
      instance_type:
        type: choice
        options:
          - g4ad.xlarge
          - g4ad.2xlarge
          - g4ad.4xlarge
          - g4ad.8xlarge
          - g4ad.16xlarge
      deploy_machine_1:
        type: boolean
        default: false
      deploy_machine_2:
        type: boolean
        default: false
      deploy_machine_3:
        type: boolean
        default: false
      deploy_machine_4:
        type: boolean
        default: false
      deploy_machine_5:
        type: boolean
        default: false
      deploy_machine_6:
        type: boolean
        default: false
      deploy_machine_7:
        type: boolean
        default: false
      deploy_machine_8:
        type: boolean
        default: false

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify.yaml

  deploy_machine_1:
    needs: verify
    if: ${{ inputs.deploy_machine_1 }}
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      stack_name: machine-1
      instance_type: ${{ inputs.instance_type }}
      windows_username: Gamer
    secrets: inherit

  deploy_machine_2:
    needs: verify
    if: ${{ inputs.deploy_machine_2 }}
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      stack_name: machine-2
      instance_type: ${{ inputs.instance_type }}
      windows_username: Gamer
    secrets: inherit

  deploy_machine_3:
    needs: verify
    if: ${{ inputs.deploy_machine_3 }}
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      stack_name: machine-3
      instance_type: ${{ inputs.instance_type }}
      windows_username: Gamer
    secrets: inherit

  deploy_machine_4:
    needs: verify
    if: ${{ inputs.deploy_machine_4 }}
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      stack_name: machine-4
      instance_type: ${{ inputs.instance_type }}
      windows_username: Gamer
    secrets: inherit

  deploy_machine_5:
    needs: verify
    if: ${{ inputs.deploy_machine_5 }}
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      stack_name: machine-5
      instance_type: ${{ inputs.instance_type }}
      windows_username: Gamer
    secrets: inherit

  deploy_machine_6:
    needs: verify
    if: ${{ inputs.deploy_machine_6 }}
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      stack_name: machine-6
      instance_type: ${{ inputs.instance_type }}
      windows_username: Gamer
    secrets: inherit

  deploy_machine_7:
    needs: verify
    if: ${{ inputs.deploy_machine_7 }}
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      stack_name: machine-7
      instance_type: ${{ inputs.instance_type }}
      windows_username: Gamer
    secrets: inherit

  deploy_machine_8:
    needs: verify
    if: ${{ inputs.deploy_machine_8 }}
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      stack_name: machine-8
      instance_type: ${{ inputs.instance_type }}
      windows_username: Gamer
    secrets: inherit
