name: Deploy

on:
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy
        run: |
          sam deploy --parameter-overrides \
            InstanceType=g4ad.xlarge \
            WindowsUsername=Gary \
            WindowsPassword=${{ secrets.WINDOWS_PASSWORD }}
