name: Lint, Test, & Deploy

on:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: scottbrenner/cfn-lint-action@v2

      - name: Lint
        run: cfn-lint **/template.yaml

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo 'Do testing here.'

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy
        run: |
          sam deploy --parameter-overrides \
            WindowsAmi=ami-03cf1a25c0360a382 \
            InstanceType=t3.large
