name: Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_little_jimmy:
        type: boolean
        default: false
      deploy_jimmy:
        type: boolean
        default: false
      deploy_big_jimmy:
        type: boolean
        default: false

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml

  deploy_little_jimmy:
    needs: verify
    if: ${{ inputs.deploy_little_jimmy }}
    name: Deploy Little Jimmy
    uses: ./.github/workflows/sam_deploy.yaml
    with:
      stack_name: little-jimmy
      instance_type: g4ad.xlarge
      windows_username: Gary
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
      windows_password: ${{ secrets.WINDOWS_PASSWORD }}

  deploy_jimmy:
    needs: verify
    if: ${{ inputs.deploy_jimmy }}
    name: Deploy Jimmy
    uses: ./.github/workflows/sam_deploy.yaml
    with:
      stack_name: jimmy
      instance_type: g4ad.2xlarge
      windows_username: Gary
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
      windows_password: ${{ secrets.WINDOWS_PASSWORD }}

  deploy_big_jimmy:
    needs: verify
    if: ${{ inputs.deploy_big_jimmy }}
    name: Deploy Big Jimmy
    uses: ./.github/workflows/sam_deploy.yaml
    with:
      stack_name: big-jimmy
      instance_type: g4ad.4xlarge
      windows_username: Gary
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
      windows_password: ${{ secrets.WINDOWS_PASSWORD }}
