name: Reusable > Destroy

on:
  workflow_call:
    inputs:
      stack_name:
        type: string
        required: true
      instance_type:
        type: string
        required: true
      windows_username:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: |
          aws cloudformation delete-stack --stack-name=${{ inputs.stack_name }}
          aws cloudformation wait stack-delete-complete --stack-name=${{ inputs.stack_name }}
