---

name: Reusable > Destroy

"on":
  workflow_call:
    inputs:
      stack_name:
        type: string
        required: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::840116000641:role/GitHub
          aws-region: ${{env.AWS_REGION}}

      - run: |
          aws cloudformation delete-stack --stack-name=${{ inputs.stack_name }}
          aws cloudformation wait stack-delete-complete --stack-name=${{ inputs.stack_name }}
