name: Reusable > Verify

on: [push, workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scottbrenner/cfn-lint-action@v2

      - run: |
          cfn-lint \
            --ignore-checks W3002 \
            --template **/*template.yaml
