---

name: Reusable > Deploy

"on":
  workflow_call:
    inputs:
      stack_name:
        type: string
        required: true
      instance_type:
        type: string
        required: true
      windows_username:
        type: string
        required: true
    secrets:
      WINDOWS_PASSWORD:
        required: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::840116000641:role/GitHub
          aws-region: ${{env.AWS_REGION}}

      - run: |
          sam deploy \
            --stack-name ${{ inputs.stack_name }} \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides \
              InstanceType=${{ inputs.instance_type }} \
              WindowsUsername=${{ inputs.windows_username }} \
              WindowsPassword=${{ secrets.WINDOWS_PASSWORD }}
