name: SAM Deploy

on:
  workflow_call:
    inputs:
      stack_name:
        type: string
      instance_type:
        type: string
      windows_username:
        type: string
    secrets:
      aws_access_key_id:
        type: string
      aws_secret_access_key:
        type: string
      aws_region:
        type: string
      windows_password:
        type: string

jobs:
  deploy:
    name: SAM Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ secrets.aws_region }}

      - run: |
          sam deploy \
            --stack-name ${{ inputs.stack_name }} \
            --region ${{ secrets.aws_region }} \
            --parameter-overrides \
              InstanceType=${{ inputs.instance_type }} \
              WindowsUsername=${{ inputs.windows_username }} \
              WindowsPassword=${{ inputs.windows_password }}
